apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.lxmusic.syncwebplayer"
        minSdkVersion 17
        targetSdkVersion 22
        versionCode 1
        versionName "1.0.0"

        // 确保原生适配 x86 及通用架构
        ndk {
            abiFilters 'x86', 'armeabi-v7a'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    
    lintOptions {
        abortOnError false
    }
}

dependencies {
    // 纯轻量化容器，无需额外引入重型三方库，保障低版本流畅度
}
