plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lxmusic.player'
    compileSdk 30

    defaultConfig {
        applicationId "com.lxmusic.player"
        minSdk 17          // 严格兼容安卓 4.2
        targetSdk 22       // 适配传统权限系统，安装即授予权限，适合老系统
        versionCode 1
        versionName "1.0.0"

        ndk {
            abiFilters 'x86' // 针对 Intel Atom 等 x86 芯片平板深度优化
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 采用原生纯净组件，减少对现代 AndroidX 复杂库的依赖，提升在 4.2 上的稳定性
}
